apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: saiep-pod-mutator
webhooks:
  - name: mutate.saiep.estin.dz
    clientConfig:
      service:
        name: saiep-webhook-svc
        namespace: default
        path: "/mutate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURNVENDQWhtZ0F3SUJBZ0lVZUtiK2hsNENpOEh2dVJIOFF2SXEwOFhjRDA4d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0tERW1NQ1FHQTFVRUF3d2RjMkZwWlhBdGQyVmlhRzl2YXkxemRtTXVaR1ZtWVhWc2RDNXpkbU13SGhjTgpNall3TmpJeU1EazFOVFV5V2hjTk1qY3dOakl5TURrMU5UVXlXakFvTVNZd0pBWURWUVFEREIxellXbGxjQzEzClpXSm9iMjlyTFhOMll5NWtaV1poZFd4MExuTjJZekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0MKQVFvQ2dnRUJBTU1IRVVpSHZUR1BrMmlaVkJjMlFMNDNQZXFncURpWTF5LzZVQVRWMkJ4ZEExN0FyMzhYTUtRegpNOFlmQ3pDRUJCamx4bkdNdm5RMml6V29MZGJybDJaTlVNWDNUUytXUlpGUmFYc2haOFE4WlhvSVJYV3F0VjhKCnRYOTBMeENLbGRNWVRhS0lBQ1RXZzhQMnRMR3BuVndtRGM1b003OVVuSjZ6eDFsMTRnZ3BSRDdpeERjbUVRcGQKZDBtdFZUV0QvK25sREpBNEpMSk5mUkZoNnNLZmRRUmlja1hSeEFRZ05WLzREMGtWVWpJUTJRVEdMcythTVZJbAoyeWN6QTU0dUZReUhmNkN3OUFqQ1M2bGlwdWRoL0ZnNmR4RGtkNDhQTzdVdmdITllCRzA1Vlhkb1Z1N2RJTmliCkNZa0pFSHZ0N2ZzUkx1QW82WUExQitOT3d4U0hIcjBDQXdFQUFhTlRNRkV3SFFZRFZSME9CQllFRkQ3NjBUTWgKQ0w0bGN2c3JudnhFNFBLa3hDTVBNQjhHQTFVZEl3UVlNQmFBRkQ3NjBUTWhDTDRsY3Zzcm52eEU0UEtreENNUApNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBS09IdUMveU5TTmVXWStDCnJTU1UzRUorTE9QcWRZeVZXNGZEY3hGeXorNlpnL3o1UVZ2OUs4cEErRCtnZjBsYU1HY0pETlkvY2lFeVJSWXQKWG1XTVlZZEw5YlNDRlQ4RnNlSTNkK1lvSjZCbnpldTY5NUowdXp4SElKZVRJMzFtbUFpaDRsNHZScnAxZXp3ZQpKd2h6K0FmcEJCZEhVVEZGaldkUTlmUkx0Q2ZBMXcxZTVNNDBhRWJSbFpzbmdDOVlYdjhDRXBCcEJEenNEeGtPCkhJSTRiK0NYeHFqUmgrT0xnOVBlZjBMQmhuc3RpYUU1c1Y4THZPVm9rcUZuKzYxeXpHcnFPVnBJTFpaOWRxUWoKUmlrRE9zaDdaTkNwNFgwSWZ2aG9kVlFUZEJIOUtxTk9OVWdrTko2UngrV2YzZ29RWTl4ZEkyZ3MrbHRKcVdGKwpjVUdTa2EwPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail # Strict enforcement: If webhook is down, pod is denied.