apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: saiep-pod-mutator
webhooks:
  - name: mutate.saiep.estin.dz
    clientConfig:
      service:
        name: saiep-webhook-svc
        namespace: default
        path: "/mutate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURoekNDQW0rZ0F3SUJBZ0lVY3UzVUZaVUdDcitmT3BsdWFhUlk2Tk5lRlNvd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0tERW1NQ1FHQTFVRUF3d2RjMkZwWlhBdGQyVmlhRzl2YXkxemRtTXVaR1ZtWVhWc2RDNXpkbU13SGhjTgpNall3TmpJek1USXhOVE0yV2hjTk1qY3dOakl6TVRJeE5UTTJXakFvTVNZd0pBWURWUVFEREIxellXbGxjQzEzClpXSm9iMjlyTFhOMll5NWtaV1poZFd4MExuTjJZekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0MKQVFvQ2dnRUJBS0VZck1KSXBFMGRhVFNvZ0xsNWpKd0RzQ2k4eVI2NGZUYVhFOXA1a2tZNUlMbmlHWjJINk1McgpCUFJZSXRqd21FbDhBZjF6WmdHc3YxTHZTQnNrc0FWRzZJQkl1ZTh0V2s5NkdxM2w0K3VnU0NBZE85TzVMeG16Cmo0SFpOdGRmQlNtaGZFcnVwK2ZMTUFDQUd6VE8rTUFYR2JHSVRFUVJ4SzZwclhJKzNIYzlNWEZLdk9xZE9MUTcKTGZUdTlFNUxhUGdYdjNhakhXcEZOR04rd01DUGJGaDJvVU5aVENpWXEyaTlXUFdKZGJ6c2NmZGNTUlVuYUh3bwovSjc1eVVrck1TRm5rQ2ovK25EMXdHQkN5djNtTDNiUlozK0FXMjV5TURQSzVXQlpKeUxqRlVERVpRYjRidzlOCmZnb3l3dlBEaStxZE5oWmM0VVNVaTUvdVcyVkxzRDBDQXdFQUFhT0JxRENCcFRDQmd3WURWUjBSQkh3d2VvSVIKYzJGcFpYQXRkMlZpYUc5dmF5MXpkbU9DR1hOaGFXVndMWGRsWW1odmIyc3RjM1pqTG1SbFptRjFiSFNDSFhOaAphV1Z3TFhkbFltaHZiMnN0YzNaakxtUmxabUYxYkhRdWMzWmpnaXR6WVdsbGNDMTNaV0pvYjI5ckxYTjJZeTVrClpXWmhkV3gwTG5OMll5NWpiSFZ6ZEdWeUxteHZZMkZzTUIwR0ExVWREZ1FXQkJRdGZRNUh6UjRnZU5ta0ZXN0oKS2FNSHlPdmtDakFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBaEUveGRwbnBDRzY4ZUNqVE5NRjFlV2w2YllXQgp5dXIwbHZRL3Zvd2xBMTk1VGcxZURpL2pEeTJ5K0FtU1NlTlljenJpTFpnbmJtNVdXZ1c0a1B1ZnRPSWdJNW4yCmlCQkM0ZXJBeTZ1RmFMZWdFNG4veWptUWFSVGxNWWE1dGxzWVo3Nk10WVFDNzJtdEFhdTZLSXBOb09GQXRCYVYKN3lieXhjdFovTFY2c1dtaHBTTkR1MlFkTXpHQWE0MHFzWDl4QlN2dHUwZlcxc3d2Q2taOE8xSVB2NUFzTFREZQpwSDJqYXlVQTIrYWtZRE9QS3FyNHozN0tqWmZJMzBaZVBOSnlPQzJva0dEUlZWanpEcjMwQVZZbkpkYXFoNUJyCnowK2tnUmZFakNBRVNEUUdLNnRRdFlpbDlLTTd5eEtla0RoNVBFL045Z0dkald1dUFVQjBENFRiVlE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail # Strict enforcement: If webhook is down, pod is denied.