apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyterhub
  namespace: argocd
spec:
  project: saiep

  source:
    repoURL: https://jupyterhub.github.io/helm-chart/
    chart: jupyterhub
    targetRevision: 3.3.7   
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: jhub

  syncPolicy:
    automated:
      prune: true
      selfHeal: true