apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: scheduler

  template:
    metadata:
      labels:
        app: scheduler

    spec:
      containers:
        - name: scheduler
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000

          env:
            - name: LOG_LEVEL
              value: {{ .Values.env.LOG_LEVEL | quote }}

          resources:
{{ toYaml .Values.resources | indent 12 }}